services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:   app_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"        # <-- changed host port
